image: emnsen/node

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -y && apt-get install rsync -y
  - "which ssh-agent || ( apt-get update -y && apt-get install rsync openssh-client -y )"
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 400 ~/.ssh
  - echo $SSH_PRIVATE_KEY > ~/.ssh/id_rsa
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\tServerAliveInterval 120\n\tTCPKeepAlive no" > ~/.ssh/config'
  - chmod 400 ~/.ssh

stages:
  - build

build_and_deploy_local:
  stage: build
  script:
    - npm install
    - npm run build
    - tar -czf app.tar.gz node_modules src dist .nvmrc ecosystem.config.js package.json
    - shipit local deploy
  only:
    - develop

#build_and_deploy_test:
#  stage: build
#  script:
#    - npm install
#    - npm run build
#    - tar -czf app.tar.gz node_modules src dist .nvmrc ecosystem.config.js package.json
#    - shipit test deploy
#  only:
#    - test
